version: '3.7'

services:
  web_horas:
    image: nginx:stable-alpine3.19-slim
    container_name: web_horas
    ports:
      - "80:80"
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - horas-server-1
    networks:
      - red-gane-int
    restart: unless-stopped

  horas-server-1:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: horas-server-1
    image: horas-server-1
    networks:
      - red-gane-int
    environment:
      - TZ=America/Bogota
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-horas_sistemas}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped

networks:
  red-gane-int:
    external: true
    
  