CREATE DATABASE IF NOT EXISTS horas_sistemas
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE horas_sistemas;

CREATE TABLE IF NOT EXISTS cargos (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(120) NOT NULL,
  descripcion VARCHAR(255) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_cargos_nombre (nombre)
);

CREATE TABLE IF NOT EXISTS personas (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  cedula VARCHAR(30) NOT NULL,
  nombres VARCHAR(120) NOT NULL,
  apellidos VARCHAR(120) NOT NULL,
  cargoId BIGINT UNSIGNED NULL,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_personas_cedula (cedula),
  KEY idx_personas_cargoId (cargoId),
  CONSTRAINT fk_personas_cargos
    FOREIGN KEY (cargoId) REFERENCES cargos (id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS registros_asistencia (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  personaId BIGINT UNSIGNED NOT NULL,
  cargoId BIGINT UNSIGNED NULL,
  fecha DATE NOT NULL,
  horaEntrada TIME NOT NULL,
  horaSalida TIME NOT NULL,
  observacion VARCHAR(255) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_registros_persona_fecha (personaId, fecha),
  KEY idx_registros_cargoId (cargoId),
  KEY idx_registros_fecha (fecha),
  CONSTRAINT fk_registros_personas
    FOREIGN KEY (personaId) REFERENCES personas (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_registros_cargos
    FOREIGN KEY (cargoId) REFERENCES cargos (id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);